/**
 * @file test_hubert_inference.cpp
 * @brief End-to-end HuBERT inference with numerical alignment vs Python reference.
 *
 * Uses real speech audio (LibriSpeech) and compares C++ output against
 * transformers HubertModel reference (generated by tools/gen_hubert_reference.py).
 *
 * Success Criterion SC-001: L2 error < 1e-4 (per-element RMS).
 */
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "voxmutatio/content/hubert_encoder.h"
#include "voxmutatio/io/audio_io.h"

namespace {

struct RefTensor {
    std::vector<int> shape;
    std::vector<float> data;
    bool ok = false;
};

// Load reference binary: [int32 ndim][int32 shape...][float32 data]
RefTensor load_reference(const std::string& path) {
    RefTensor ref;
    std::ifstream ifs(path, std::ios::binary);
    if (!ifs.is_open()) return ref;

    int32_t ndim = 0;
    ifs.read(reinterpret_cast<char*>(&ndim), 4);
    if (ndim <= 0 || ndim > 8) return ref;

    int64_t total = 1;
    for (int i = 0; i < ndim; ++i) {
        int32_t s = 0;
        ifs.read(reinterpret_cast<char*>(&s), 4);
        ref.shape.push_back(s);
        total *= s;
    }

    ref.data.resize(total);
    ifs.read(reinterpret_cast<char*>(ref.data.data()), total * sizeof(float));
    ref.ok = ifs.good() || ifs.eof();
    return ref;
}

// Per-element RMS of the difference
double rms_error(const std::vector<float>& a, const std::vector<float>& b) {
    if (a.size() != b.size() || a.empty()) return -1.0;
    double sum_sq = 0.0;
    for (size_t i = 0; i < a.size(); ++i) {
        double d = static_cast<double>(a[i]) - static_cast<double>(b[i]);
        sum_sq += d * d;
    }
    return std::sqrt(sum_sq / a.size());
}

// Max absolute difference
double max_abs_diff(const std::vector<float>& a, const std::vector<float>& b) {
    double mx = 0.0;
    for (size_t i = 0; i < a.size() && i < b.size(); ++i) {
        mx = std::max(mx, std::abs(static_cast<double>(a[i]) - b[i]));
    }
    return mx;
}

}  // namespace

TEST_CASE("HuBERT v2 numerical alignment (layer 12)", "[hubert][alignment]") {
    using namespace voxmutatio;

    std::string model_path = "../models/hubert_base/model.safetensors";
    std::string audio_path = "../tests/fixtures/speech_librispeech.wav";
    std::string ref_path = "../tests/fixtures/hubert_ref_layer12.bin";

    // Load real speech audio
    auto audio = io::read_audio(audio_path);
    REQUIRE(audio.has_value());
    REQUIRE(!audio->data.empty());
    std::cout << "Audio: " << audio->data.size() << " samples @ "
              << audio->sample_rate << " Hz" << std::endl;

    // Load Python reference
    auto ref = load_reference(ref_path);
    REQUIRE(ref.ok);
    REQUIRE(ref.shape.size() == 2);
    int ref_T = ref.shape[0];
    int ref_D = ref.shape[1];
    std::cout << "Reference: [" << ref_T << ", " << ref_D << "]" << std::endl;
    REQUIRE(ref_D == 768);

    // Run C++ HuBERT (v2: 768-dim, no final proj)
    content::HubertConfig config;
    config.model_path = model_path;
    config.output_dim = 768;
    config.use_final_proj = false;

    content::HubertEncoder encoder;
    REQUIRE(encoder.init(config));

    auto features = encoder.extract(audio->data.data(),
                                    static_cast<int>(audio->data.size()));
    REQUIRE(!features.empty());
    REQUIRE(features.size() % 768 == 0);

    int cpp_T = static_cast<int>(features.size()) / 768;
    std::cout << "C++ output: [" << cpp_T << ", 768]" << std::endl;

    // Frame count must match
    REQUIRE(cpp_T == ref_T);
    REQUIRE(features.size() == ref.data.size());

    // Numerical alignment
    double rms = rms_error(features, ref.data);
    double max_diff = max_abs_diff(features, ref.data);
    std::cout << "RMS error: " << rms << std::endl;
    std::cout << "Max abs diff: " << max_diff << std::endl;

    // SC-001: L2 error < 1e-4
    CHECK(rms < 1e-4);
}

TEST_CASE("HuBERT v1 numerical alignment (final proj 256)", "[hubert][alignment][v1]") {
    using namespace voxmutatio;

    std::string model_path = "../models/hubert_base/model.safetensors";
    std::string audio_path = "../tests/fixtures/speech_librispeech.wav";
    std::string ref_path = "../tests/fixtures/hubert_ref_v1_final256.bin";

    auto audio = io::read_audio(audio_path);
    REQUIRE(audio.has_value());

    auto ref = load_reference(ref_path);
    REQUIRE(ref.ok);
    REQUIRE(ref.shape.size() == 2);
    REQUIRE(ref.shape[1] == 256);

    content::HubertConfig config;
    config.model_path = model_path;
    config.output_dim = 256;
    config.use_final_proj = true;

    content::HubertEncoder encoder;
    REQUIRE(encoder.init(config));

    auto features = encoder.extract(audio->data.data(),
                                    static_cast<int>(audio->data.size()));
    REQUIRE(!features.empty());
    REQUIRE(features.size() == ref.data.size());

    double rms = rms_error(features, ref.data);
    double max_diff = max_abs_diff(features, ref.data);
    std::cout << "v1 RMS error: " << rms << std::endl;
    std::cout << "v1 Max abs diff: " << max_diff << std::endl;

    CHECK(rms < 1e-4);
}
